export const categories = [
  {
    name: 'Prelims',
    subcategories: [
      'Current events of national and international importance',
      'History of India and Indian National Movement',
      'Indian and World Geography',
      'Indian Polity and Governance',
      'Economic and Social Development',
      'Environmental Ecology, Biodiversity, and Climate Change',
      'General Science',
      'Comprehension',
      'Interpersonal skills including communication skills',
      'Logical reasoning and analytical ability',
      'Decision-making and problem solving',
      'General mental ability',
      'Basic numeracy and Data interpretation'
    ]
  },
  {
    name: 'Mains',
    subcategories: [
      'Indian Heritage and Culture',
      'Modern Indian history',
      'The Freedom Struggle',
      'Post-independence consolidation',
      'World History',
      'Indian Society and Diversity',
      'Role of women and women\'s organization',
      'Population and associated issues',
      'Poverty and developmental issues',
      'Urbanization',
      'Effects of globalization on Indian society',
      'Social empowerment, communalism, regionalism & secularism',
      'World\'s physical geography',
      'Distribution of key natural resources',
      'Important Geophysical phenomena',
      'Indian Constitution',
      'Functions and responsibilities of the Union and the States',
      'Separation of powers',
      'Parliament and State legislatures',
      'Executive and the Judiciary',
      'Representation of People\'s Act',
      'Constitutional posts',
      'Statutory, regulatory and quasi-judicial bodies',
      'Government policies and interventions',
      'Development processes',
      'Welfare schemes',
      'Issues relating to development of Social Sector/Services',
      'Issues relating to poverty and hunger',
      'Governance, transparency and accountability',
      'Role of civil services in a democracy',
      'India and its neighbourhood relations',
      'Bilateral, regional and global groupings',
      'Indian Economy',
      'Government Budgeting',
      'Major crops and irrigation systems',
      'Issues related to farm subsidies and food security',
      'Food processing industries',
      'Land reforms in India',
      'Effects of liberalization on the economy',
      'Infrastructure',
      'Science and Technology developments',
      'Achievements of Indians in science & technology',
      'Awareness in IT, Space, Computers, robotics, nano-technology, bio-technology',
      'Intellectual property rights',
      'Conservation and environmental issues',
      'Disaster management',
      'Internal security challenges',
      'Role of external state and non-state actors',
      'Cyber security and money-laundering',
      'Security challenges in border areas',
      'Various Security forces and agencies'
    ]
  },
  {
    name: 'Interview',
    subcategories: [
      'Personal Suitability',
      'Mental Qualities',
      'Analytical Ability',
      'Current Affairs',
      'Situational Analysis',
      'Problem-Solving Skills',
      'Leadership Qualities',
      'Ethical Decision Making',
      'Communication Skills'
    ]
  },
  {
    name: 'Blog',
    subcategories: [
      'Study Tips',
      'Exam Strategies',
      'Current Affairs Analysis',
      'Success Stories',
      'Book Reviews',
      'Interview Experiences',
      'Optional Subject Insights',
      'Preparation Schedules',
      'Motivation and Well-being'
    ]
  }
]